### ISSUE TITLE
Peer Review 2

### ISSUE THREAD

**Issue by palmerlarson** [PRBergerIII/entJavaIndyProject#6]
|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
 N/A | Planned MVP Functionality |  Doesn't look like you reached full MVP coverage but I'm sure you will upon completion! |
 Y | Logging framework used, i.e., no System.out.println() or printStacktrace() statements. | Looks like log4j is setup, log folder gitignore |
  Y | Hibernate used for all data access. | properties added to gitignore, great! |
 N | Authentication implemented. | Doesn't look to be set up yet. I'd recommend watching the vids related to this: http://paulawaite.com/education/java113/Module2/Week7/Auth.html as they helped me out a lot. Also as Paula was explaining to me, it's easiest to authentication then start a session rather than continuously authenticating each servlet.  |
 N/A | Consumes at least one web service or public api using Java. |  
 Y | Application is database-driven using full CRUD. |  
 Y | Database includes multiple one to many relationships. | user -> many |
 N | Deployed to AWS for public access. |  |
  Y | Implements best practices (for example, data validation) | Best practices seem to be looking good so far outside of missing comments. |
N/A  | Synthesis of multiple concepts in unfamiliar situations requiring research beyond the scope of the class |  
 N/A | Experiments individually, exhibits independence and drive, shows originality in the solution. |  
 Y | Implemented technologies or techniques not covered in course materials. | I'm not sure if Bootstrap counts, but using a CSS framework like bootstrap will allow for faster frontend dev. |
 Y | Code quality - Evaluate code quality for the following and identify specific areas for improvement (class, method or line number). Be sure to list which code quality plugins/tools you used to assist with this analysis | Quality seen has been good and standard to the course so far. Keep it up! |
N/A  | Single-purpose methods |  
Y  | Well-structured project | Project structure is clean and uncluttered. Good use of gitignore. |
 Y | Descriptive naming of packages, classes, methods, variables | Naming seems great so far! |
Y  | Classes appropriately-sized (no monster classes) | Class sizes are minimal right now. |
 N/A | CPD (copy paste detection, meaning are the same lines of code repeated? |  
 N/A | Are there candidates for super/subclass relationships, abstract classes, interfaces |  
 N/A | Proper exception handling |  
 N/A | Proper error reporting to the user - custom erro pages? |  
 N | Code documentation | I'd recommend generating comments for each of the classes and generating a JavaDoc as well. If you're like me, you probably do that last. I need to break that habit as well too and do it continuously. |
 N/A | Is there code in the servlet doGet/doPost that should be refactored into testable classes or methods? | I'm not seeing any servlet classes yet, sorry if I missed them. I recommend throwing those into a controller package once you get started on those. |
 Y | Evaluate the JSPs for templating, data validation, overall look and feel. | Everything looks to be pretty basic so far. Bootstrap is being used as a framework which will allow for quicker frontend development. |
Y  | JSPs use JSTL and EL, no java code | Nice work on using includes! |
 Y | Unit tests are truly a unit test rather than a high level functional test |  
 Y | Test data is appropriately cleaned up or handled |  |
 N/A | There is full coverage of methods that perform business logic or utility functions |  
  | Other comments/notes? | Hey Paul, that's about as much as I think I can review for this so far. It looks like you have a great start on your indie project, though it looks like you have a ways to go. I'd recommend getting your Cognito or Authentication service set up sooner rather than later before the due date as that was the biggest time sink for me attempting to get that how I wanted it. Your dB design looks nice as well. I'm thinking you might need to throw in a little bit of JS for real time updating for the lists. <br><br> Overall, you have a lot of work to do between now and the due date I don't doubt that you can do it. You have a great start and an idea of where you want to be. Good luck on the grind, let me know if you need help with anything!

**Comment by PRBergerIII** [comment]
Thanks man! Long way to go yet, but I appreciate you taking a look. Good luck on yours!
